apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  namespace: docker-influxdb-grafana
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: ec2-63-33-190-1.eu-west-1.compute.amazonaws.com
      http:
        paths:
          - path: /
            backend:
              serviceName: grafana-service
              servicePort: 3000
