apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  namespace: docker-influxdb-grafana
  annotations:
    INGRESS.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: ec2-63-33-190-1.eu-west-1.compute.amazonaws.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: grafana-service
                port:
                  number: 8080
