apiVersion: apps/v1
kind: Deployment
metadata:
  name: disk-usage-cronjob-deployment
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: disk-usage-cronjob
  template:
    metadata:
      labels:
        app: disk-usage-cronjob
    spec:
      containers:
        - image: python:3.8-slim-buster
          name: disk-usage-cronjob
          stdin: true
          tty: true
          # args:
          # - sh
          # - -c
          # - "/wait-for-it.sh $${INFLUXDB_CONTAINER_HOST}:$${INFLUXDB_CONTAINER_PORT} --strict -- sshpass -p $${INFLUXDB_CONTAINER_PASSWORD} ssh-copy-id -i /root/.ssh/id_rsa.pub -o StrictHostKeyChecking=no $${INFLUXDB_CONTAINER_USER}@$${INFLUXDB_CONTAINER_HOST} &&
          #   python main.py"
      restartPolicy: Always
