apiVersion: v1
kind: Pod
metadata:
  name: cronjob-pod
  namespace: app
  labels:
    app: cronjob
spec:
  containers:
    - name: cronjob
      image: muhadel/disk_usage_cronjob
      args:
        - sh
        - -c
        - "/wait-for-it.sh $${INFLUXDB_CONTAINER_HOST}:$${INFLUXDB_CONTAINER_PORT} --strict -- sshpass -p $${INFLUXDB_CONTAINER_PASSWORD} ssh-copy-id -i /root/.ssh/id_rsa.pub -o StrictHostKeyChecking=no $${INFLUXDB_CONTAINER_USER}@$${INFLUXDB_CONTAINER_HOST} &&
          python main.py"
