apiVersion: v1
kind: Pod
metadata:
  name: cronjob-pod
  namespace: app
  labels:
    app: cronjob
spec:
  containers:
    - name: cronjob
      image: muhadel/disk_usage_cronjob
      args:
        - sh
        - -c
        - "echo $${INFLUXDB_URL} &&
          /wait-for-it.sh -h $${INFLUXDB_CONTAINER_HOST} -p $${INFLUXDB_CONTAINER_PORT} -s -- sshpass -p $${INFLUXDB_CONTAINER_PASSWORD} ssh-copy-id -i /root/.ssh/id_rsa.pub -o StrictHostKeyChecking=no $${INFLUXDB_CONTAINER_USER}@$${INFLUXDB_CONTAINER_HOST} &&
          python main.py"
      env:
        - name: INFLUXDB_URL
          valueFrom:
            configMapKeyRef:
              key: INFLUXDB_URL
              name: env-cronjob
        - name: INFLUXDB_USERNAME
          valueFrom:
            configMapKeyRef:
              key: INFLUXDB_USERNAME
              name: env-cronjob
        - name: INFLUXDB_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: INFLUXDB_PASSWORD
              name: env-cronjob
        - name: INFLUXDB_ORG
          valueFrom:
            configMapKeyRef:
              key: INFLUXDB_ORG
              name: env-cronjob
        - name: INFLUXDB_BUCKET
          valueFrom:
            configMapKeyRef:
              key: INFLUXDB_BUCKET
              name: env-cronjob
        - name: INFLUXDB_ADMIN_TOKEN
          valueFrom:
            configMapKeyRef:
              key: INFLUXDB_ADMIN_TOKEN
              name: env-cronjob
        - name: INFLUXDB_CONTAINER_HOST
          valueFrom:
            configMapKeyRef:
              key: INFLUXDB_CONTAINER_HOST
              name: env-cronjob
        - name: INFLUXDB_CONTAINER_PORT
          valueFrom:
            configMapKeyRef:
              key: INFLUXDB_CONTAINER_PORT
              name: env-cronjob
        - name: INFLUXDB_CONTAINER_USER
          valueFrom:
            configMapKeyRef:
              key: INFLUXDB_CONTAINER_USER
              name: env-cronjob
        - name: INFLUXDB_CONTAINER_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: INFLUXDB_CONTAINER_PASSWORD
              name: env-cronjob
