apiVersion: v1
kind: Pod
metadata:
  name: grafana-pod
  namespace: app
  labels:
    app: grafana
spec:
  containers:
    - name: grafana
      image: grafana/grafana
      # args:
      #   - sh
      #   - -c
      #   - "echo ';serve_from_sub_path = true' >> /etc/grafana/grafana.ini &&
      #     grafana-server"
