apiVersion: v1
kind: Service
metadata:
  name: cronjob-service
  namespace: app
spec:
  type: ClusterIP
  ports:
    - name: cronjob-port
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: cronjob
