apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: myapp
spec:
  type: ClusterIP
  ports:
    - name: grafana-port
      targetPort: 3000
      port: 8080
  selector:
    app: grafana
