apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  # Default Service Type
  type: ClusterIP
  ports:
    - name: "grafana-port"
      targetPort: 3000
      port: 3000
  selector:
    app: grafana
