apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: app
spec:
  type: ClusterIP
  ports:
    - name: grafana-port
      protocol: TCP
      port: 80
      targetPort: 3000
  externalIPs:
    - 63.33.190.1
  selector:
    app: grafana
