apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  namespace: app
spec:
  type: ClusterIP
  ports:
    - name: influxdb-port
      protocol: TCP
      port: 8086
      targetPort: 8086
  selector:
    app: influxdb
